spring.application.name=apiGateway-server


server.port=8085


# Discovery con Eureka
spring.cloud.gateway.discovery.locator.enabled=true

# Ruta hacia Flota-Service
spring.cloud.gateway.routes[0].id=flota-route
spring.cloud.gateway.routes[0].uri=lb://FLOTA-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/flotas/**