spring.application.name=cotizador-servicer


server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cotizaciondb
spring.datasource.username=postgres
spring.datasource.password=Rubio_456123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect